version: '3.8'
 
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gameshop
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - "mariadb_data:/var/lib/mysql"
    restart: unless-stopped
volumes:
  mariadb_data: